server:
  port: 8080
  logging: WARN
  jettyContainerThreads: 200
  jettyAcceptors: 3
  jettyAcceptQueueSize: 100
  jettyHeaderBufferSize: 16834
  maxRequestJournalEntries: 5

db:
  host: localhost
  port: 27017
  database: test
  username: tester
  password: xyz123
  collection: mock

cluster:
  baseSleepTimeMills: 2000
  maxRetires: 4
  waitTimeSeconds: 2000
  sessionTimeout: 20000
  connectionTimeout: 20000
  host: localhost:2181